name: Reach Admin Pipeline

on: 
   push:
     branches: [ deployment, main ]
   pull_request: 
     branches: [ deployment, main ]

jobs:
  staging:  
    name: PURELIFE PHARMACY FRONTEND
    runs-on: ubuntu-latest 
    steps:
      - name: remote ssh commands 
        if: ${{ github.ref == 'refs/heads/deployment' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PURELIFE_SERVER }}
          username: ${{ secrets.PURELIFE_USER }}
          key: ${{ secrets.PURELIFE_KEY }}
          port: ${{ secrets.PURELIFE_PORT }}
          script: |
             cd /usr/Purelife-Pharmacy-Project
             git pull origin deployment
             docker build -t purelife-frontend .
             docker rm -f purelife-frontend
             docker run --name purelife-frontend --restart always -d -p 3400:3000 --env-file ./.env purelife-frontend
          
