name: Reach Admin Pipeline

on:
  push:
    branches: [deployment, boluDev]
  pull_request:
    branches: [deployment, boluDev]

jobs:

  staging:
    name: PURELIFE PHARMACY FRONTEND
    runs-on: ubuntu-latest

    steps:
    - name: Remote SSH Commands (Deployment)
      if: ${{ github.ref == 'refs/heads/deployment' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PURELIFE_SERVER }}
        username: ${{ secrets.PURELIFE_USER }}
        key: ${{ secrets.PURELIFE_KEY }}
        port: ${{ secrets.PURELIFE_PORT }}
        script: |
          cd /usr/Purelife-Pharmacy-Project
          git pull origin deployment
          docker build -t purelife-frontend .
          docker rm -f purelife-frontend
          docker run --name purelife-frontend --restart always -d -p 3400:3000 --env-file ./.env purelife-frontend

  production:
    name: PURELIFE dev
    runs-on: ubuntu-latest

    steps:
    - name: Remote SSH Commands (dev)
      if: ${{ github.ref == 'refs/heads/boluDev' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FI_SERVER }}
        username: ${{ secrets.FI_USER }}
        key: ${{ secrets.FI_KEY }}
        port: ${{ secrets.FI_PORT }}
        script: |
          cd /usr/fi-server-project/Purelife-Pharmacy-Project
          sudo git pull origin boluDev
          sudo docker build -t purelife-frontend .
          sudo docker rm -f purelife-frontend
          sudo docker run --name purelife-frontend --restart always -d -p 3400:3000 purelife-frontend
